services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./api"]
    ports:
      - "8080:8080"
    volumes:
      - .env:/app/.env
    env_file: .env
    restart: on-failure
    depends_on:
      postgres:
        condition: service_started
    environment:
      - SERVER_PORT=8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:16-alpine3.19
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: myuser  # Make sure this matches the username in the connection string
      POSTGRES_PASSWORD: mypassword  # Make sure this matches the password in the connection string
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  mailpit: # For email sending tests
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_REQUIRE_STARTTLS: 1
      MP_SMTP_TLS_CERT: /data/cert.pem
      MP_SMTP_TLS_KEY: /data/key.pem

volumes:
  postgres_data:
  data:
