services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./api"]
    ports:
      - "8080:8080"
    volumes:
      - .env:/app/.env
    env_file: .env
    restart: on-failure
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_started
    environment:
      - SERVER_PORT=8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  asyncq:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./asyncq
    volumes:
      - .env:/app/.env
    depends_on:
      redis:
        condition: service_started
    env_file: .env
    restart: on-failure
    environment:
      - REDIS_ADDR=redis:6379

  redis:
    image: redis:7.2.4-alpine3.19
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine3.19
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  asyncqmon:
    image:  hibiken/asynqmon
    ports:
      - 5555:5555
    command: ["--port", "5555", "--redis-addr", "redis:6379", "--redis-db", "0"]
    depends_on:
      redis:
        condition: service_started

  mailpit: # For email sending tests
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_REQUIRE_STARTTLS: 1
      MP_SMTP_TLS_CERT: /data/cert.pem
      MP_SMTP_TLS_KEY: /data/key.pem

volumes:
  postgres_data:
  data:
